# Generated by Django 3.0.7 on 2020-08-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('press_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='petname',
            new_name='pet_name',
        ),
    ]
