# Generated by Django 3.0.7 on 2020-08-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200813_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='app01.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app01.Press'),
            preserve_default=False,
        ),
    ]
